### ISSUE TITLE
UI Reflow Error - New Chart Step 2 'Metrics' Pill Selections Shouldn't overflow out-of-bounds

### ISSUE THREAD

**Issue by inn-0** [pydantic/logfire#112]
### Description

When creating a New Chart (e.g. pie chart), at Step 3, selecting many metrics leads to overflowing horizontally. These should instead reflow within the bounds. 🙂

![image](https://github.com/pydantic/logfire/assets/132111523/0ee77a64-3469-4e90-82c3-4eefd252a056)

Also the last step is labelled as "Step 2" though it should be "Step 3".
_No response_

**Comment by e-hosseini** [comment]
The issue has been fixed.
Thank you, @inn-0, for reporting.
