### ISSUE TITLE
EdgeDB Integration?

### ISSUE THREAD

**Issue by samuelcolvin** [pydantic/logfire#116]
### Description

I was talking to @elprans on on LinkedIn.

The integration would be the similar to SQL DB integrations, but show the EdgeDB query?

(Maybe off topic) Would be good to put a span around transactions? This question applies to any db integration.

**Comment by Kludex** [comment]
@samuelcolvin should we close this? There was no one interested in this since May. We can reopen if someone is interested... 👀

**Comment by Kludex** [comment]
It doesn't seem that EdgeDB has much usage in Python.

<img width="1213" alt="Screenshot 2024-12-24 at 10 45 00" src="https://github.com/user-attachments/assets/9b51df39-af71-4ffc-b875-fd6b6779dfa9" />

Also, no one reacted to this issue. I'll be closing it for the time being. If someone is interested, please let us know, and we can reopen and work on this integration. On a side note, I saw OpenTelemetry support on EdgeDB's roadmap.
