### ISSUE TITLE
[question] Traceback UI

### ISSUE THREAD

**Issue by elisalimli** [pydantic/logfire#117]
### Question

What's the correct way to set the exception in Python, so UI can render it properly?

<img width="823" alt="image" src="https://github.com/pydantic/logfire/assets/67149699/562feab3-fc7b-4932-bb44-6896009e45e1">

<img width="847" alt="image" src="https://github.com/pydantic/logfire/assets/67149699/a92cea04-8e55-4215-9518-585a5f600b8e">

This looks empty right now, according to the docs I'm setting exc_info:
```py
try:
   ...
except Exception as e:
   logfire.error("My error log", exc_info=e)
```

**Comment by alexmojaki** [comment]
It's `_exc_info`. All 'special' keyword arguments have a leading underscore to distinguish them from attributes. Maybe we should emit a warning when someone passes an attribute that looks like it was meant to be a special keyword arg.

You can also just do this:

```python
try:
   ...
except Exception:
   logfire.exception("My error log")
```

`logfire.exception("My error log")` is equivalent to `logfire.error("My error log", _exc_info=True)` and `_exc_info=True` gets the currently handled exception so you don't have to pass it.

**Comment by elisalimli** [comment]
> It's `_exc_info`. All 'special' keyword arguments have a leading underscore to distinguish them from attributes. Maybe we should emit a warning when someone passes an attribute that looks like it was meant to be a special keyword arg.
> 
> You can also just do this:
> 
> ```python
> try:
>    ...
> except Exception:
>    logfire.exception("My error log")
> ```
> 
> `logfire.exception("My error log")` is equivalent to `logfire.error("My error log", _exc_info=True)` and `_exc_info=True` gets the currently handled exception so you don't have to pass it.

Right, now it renders properly. Thanks!
