### ISSUE TITLE
Redacting content that isn't private

### ISSUE THREAD

**Issue by bllchmbrs** [pydantic/logfire#123]
### Description

Right now I've got some content that I want to print in logfire, but it's being redacted as private, but there's nothing private!

I imagine what is triggering it is the word `dotenv` or `env`.

It strikes me as overly sensitive and I don't see a way to configure it.

**Comment by alexmojaki** [comment]
See https://docs.pydantic.dev/logfire/guides/advanced/scrubbing/#scrubbing-less-with-a-callback

**Comment by Kludex** [comment]
Does that documentation solve your issue, @bllchmbrs ?

**Comment by bllchmbrs** [comment]
All good, thanks!
