### ISSUE TITLE
logfire auth

### ISSUE THREAD

**Issue by kenmoh** [pydantic/logfire#125]
### Question

I was trying logfire on a FastAPI app hosted on render.com, I got "You're not authenticate, run logfire auth" on the render log.
So, is a way I can pass the auth credential a environment variable?

**Comment by Kludex** [comment]
Hi @kenmoh,

The idea is to create a write token, and set the `LOGFIRE_TOKEN` environment variable there.

You can read more about it [here](https://docs.pydantic.dev/logfire/guides/advanced/creating_write_tokens/).

**Comment by kenmoh** [comment]
Oh great! Thank you @Kludex .
