### ISSUE TITLE
Ignore stdlib logs from urllib3

### ISSUE THREAD

**Issue by alexmojaki** [pydantic/logfire#135]
https://pydanticlogfire.slack.com/archives/C06EDRBSAH3/p1713885605381719

We can specifically ignore the message `https://logfire-api.pydantic.dev:443 "POST /v1/traces HTTP/1.1" 200 2` (and same for `/v1/metrics`) so that the user doesn't have to silence all of urllib3 to avoid this noise.

**Comment by epicwhale** [comment]
+1 👍

**Comment by epicwhale** [comment]
fyi: when I put this into my fastapi project, I realised the noise is VERY HIGH - almost takes over the entire real estate.. 
![image](https://github.com/pydantic/logfire/assets/670655/b7325d9e-4be8-4b32-a91f-a9d6e61163b6)

**Comment by adriangb** [comment]
Shouldn't the urllib3 instrumentation respect the contextvars to not infinite loop instrumentation? Are we maybe not propagating them correctly?

**Comment by alexmojaki** [comment]
This is urllib3 using stdlib logging, i.e. this fix would be in the stdlib logging instrumentation. The urllib3 instrumentation is not involved.

But you do bring up a good point. Looking more closely, we use the string `suppress_instrumentation`, whereas OTEL mostly uses `_SUPPRESS_INSTRUMENTATION_KEY = create_key("suppress_instrumentation")` which is different.

**Comment by adriangb** [comment]
OTEL currently has a haphazard mix of suppress instrumentation keys. We should probably just set all of them.

**Comment by alexmojaki** [comment]
Well in this case it's about reading the correct key. OTEL conveniently sets it in the right places in BatchSpanProcessor and SimpleSpanProcessor.

**Comment by alexmojaki** [comment]
Fixed by https://github.com/pydantic/logfire/pull/197
