### ISSUE TITLE
Generate metric points from pydantic class changes?

### ISSUE THREAD

**Issue by inimaz** [pydantic/logfire#145]
### Question

Hello team! thanks for the great tool.

I haven't found it in the docs and maybe it is a use case you might be interested in covering? I have a `pydantic` class and I want to create a gauge/counter metric point out of it every time its value gets updated.

In the docs I see you have an integration detecting the validation results, so maybe there is a way already?

Thanks a lot.

**Comment by Kludex** [comment]
We have that already! 

The name of the metric is "pydantic.validations". We are recording this information:

https://github.com/pydantic/logfire/blob/a5026b1fd57e7a99daecaaa8c7613c97a01a7d32/logfire/integrations/pydantic.py#L258-L260

What's your use case? Do you want to create some dashboard? We are interested. 👀

**Comment by inimaz** [comment]
Good to know! But that counter counts the number of times it does the validation. Sorry for the misunderstanding. Instead I would like to monitor the value of the updated field.
For example if I have this:
```
from pydantic import BaseModel

class Temperature(BaseModel):
    value: int = 22
```
Every time someone does `Temperature(value=27)` ==> metric point with value 27.
Right now the way to do this is to create the metric yourself using `otel` and then pass this metric to `logfire` I guess?

**Comment by alexmojaki** [comment]
Here's what you can do:

```python
import pydantic

import logfire

gauge = logfire.DEFAULT_LOGFIRE_INSTANCE._config.meter.create_gauge('temperature')


class Temperature(pydantic.BaseModel, validate_assignment=True):
    value: int

    @pydantic.field_validator('value')
    def validate_value(cls, value):
        gauge.set(value)
        return value


t = Temperature(value=1)
t.value = 2
```

`create_gauge` is a new OTEL method, we should add a `logfire.metric_gauge` method.

**Comment by alexmojaki** [comment]
BTW you can now write `gauge = logfire.metric_gauge('temperature')`.
