### ISSUE TITLE
Support pydantic v1

### ISSUE THREAD

**Issue by alexmojaki** [pydantic/logfire#147]
https://pydanticlogfire.slack.com/archives/C06EDRBSAH3/p1715039582297379

It doesn't have to be rendered nicely, but it shouldn't break.

**Comment by alexmojaki** [comment]
Another case of this breaking things for a user: https://pydanticlogfire.slack.com/archives/C06EDRBSAH3/p1715089742992309?thread_ts=1715088823.604819&cid=C06EDRBSAH3

**Comment by mkoci-scala** [comment]
Wow, thanks for being so proactive on this!
