### ISSUE TITLE
Sort observations in descending order in live dashboard

### ISSUE THREAD

**Issue by josca42** [pydantic/logfire#159]
### Description

Thanks for creating logfire!. It really is the logging library I always wanted :-).

I really like using the Live dashboard view when developing/testing code/endpoints etc. But would be really nice to have the observations ordered by descending order as default since I'm nearly always interested in the latest observations. Would also remove the need to always load a lot of data, when the live dashboard automatically scrolls to the latest observations.

**Comment by e-hosseini** [comment]
@josca42 Thank you for your feedback. 
The Live View is currently sorted in ascending order. However, new logs are being added at the end of the list. If you are unable to view your latest logs at the end of the list, please try enabling 'Live Tails'. This feature should assist you in finding what you are looking for.
<img width="182" alt="image" src="https://github.com/pydantic/logfire/assets/53467610/b1232f10-f702-4c9a-b3a6-25c509a97216">
