### ISSUE TITLE
Poetry Install of fastAPI didn't work (according to docs)

### ISSUE THREAD

**Issue by bllchmbrs** [pydantic/logfire#165]
### Description

I tried following[ the docs on the fastapi install ](https://docs.pydantic.dev/logfire/integrations/fastapi/?h=fasta)with poetry but it didn't work.

This worked:`poetry add 'logfire[fastapi]'`

This, didn't:
```
poetry add logfire -E fastapi
The following packages are already present in the pyproject.toml and will be skipped:

  • logfire

If you want to update it to the latest compatible version, you can use `poetry update package`.
If you prefer to upgrade it to the latest available version, you can use `poetry add package@latest`.

Nothing to add.
```

Not sure if this is user error, but others may get caught up

I found out that to add this as well as the psycopg one, I had to run

`poetry add "logfire[fastapi.psycopg2]"`
Nothing else worked. You probably want to update the docs.

**Comment by Kludex** [comment]
Hmm... I followed poetry docs for that part, and it actually works on version 1.8.2.

I'll change to `logfire[fastapi]` way if has more compatibility with older versions. 👍
