### ISSUE TITLE
Save query / Download / from remote

### ISSUE THREAD

**Issue by bllchmbrs** [pydantic/logfire#171]
### Question

I want to use logfire to collect traces during LLM execution. I want to use these later for fine tuning.

I see no way to download a "dataset" from the UI, nor save a query, nor run from the SDK... something, conceptually like:

```
from logfire import data

res = data.query("SELECT * FROM records")
df = res.to_pandas_df()
....
```

This might be a feature request, but it seems relatively self-evident - am I thinking about logfire in the right way?

**Comment by alexmojaki** [comment]
In the 'Explore' view there used to be a way to download SQL query results as a CSV, but it's disappeared in a recent reworking of the UI. For now all you can do there is click the corner of the table (selecting all cells) and copy, which puts a TSV in your clipboard.

You can also connect to the database directly: https://docs.pydantic.dev/logfire/guides/advanced/direct_database_connections/

To add another example to those docs:

```python
import psycopg

conn = psycopg.connect('postgresql://...')
cursor = conn.cursor()
cursor.execute('SELECT * FROM records LIMIT 50')
for row in cursor.fetchall():
    print(row)
```

Right now `pandas.read_sql` won't work but that should be fixed soon.

**Comment by bllchmbrs** [comment]
ok, thanks.

I guess from a user perspective I don't want a "direct database connection" I want to "query my logfire data" - might be helpful for naming.

This seems really great though, excited to use it!
