### ISSUE TITLE
`logfire.instrument_*()` methods

### ISSUE THREAD

**Issue by alexmojaki** [pydantic/logfire#193]
e.g. `logfire.instrument_sqlalchemy()` instead of `from opentelemetry.instrumentation.sqlalchemy import SQLAlchemyInstrumentor; SQLAlchemyInstrumentor().instrument()`. Same for all integrations documented in https://docs.pydantic.dev/logfire/integrations/#opentelemetry-integrations.

**Comment by alexmojaki** [comment]
Remaining methods to add:

- [ ] `logfire.instrument_flask()`
- [ ] `logfire.instrument_starlette()`
- [ ] `logfire.instrument_aiohttp()`
- [ ] `logfire.instrument_sqlalchemy()`
- [ ] `logfire.instrument_pymongo()`
- [ ] `logfire.instrument_redis()`
- [ ] `logfire.instrument_celery()`
- [ ] `logfire.instrument_asgi_middleware()`
- [ ] `logfire.instrument_wsgi_middleware()`
- [ ] `logfire.instrument_logging_handler()`
- [ ] `logfire.instrument_loguru_handler()`
- [ ] `logfire.instrument_structlog_processor()`

I'm not sure about the names of the last 5. It is important that they're methods of logfire objects rather than classes imported from logfire. It would be nice for everything to start with `instrument_` but `instrument_logging_handler` sounds like it's instrumenting a logging handler, rather than returning a handler that 'instruments logging'.

@Kludex I'm going to start working on the first 6, please do the other half.

**Comment by alexmojaki** [comment]
@Kludex I think we should have `logfire.instrument_loguru()` which calls `logger.add(**logfire.loguru_handler())`. That makes the naming less weird and should be easier for users, avoiding problems like https://github.com/pydantic/logfire/issues/228. `logfire.loguru_handler()` can be kept for compatibility but not recommended.

**Comment by Kludex** [comment]
Is this done? @alexmojaki

**Comment by alexmojaki** [comment]
No because I did half and I asked you to do the other half.

**Comment by Kludex** [comment]
About the ASGI and WSGI, I'm not sure if it makes sense to create those methods.

Maybe wrapping them, and providing a `logfire.InstrumentASGIMiddleware` and `logfire.InstrumentWSGIMiddleware` makes more sense. wdyt @alexmojaki ?

**Comment by alexmojaki** [comment]
They need to be methods so that you can use them with different logfire objects that have different configs.

We could maybe just call them `instrument_asgi/wsgi`. Then the docs would suggest `app = instrument_asgi(app)` which doesn't look weird. It's only 'middleware' in the context of higher level frameworks which choose that terminology. For example the starlette OTEL instrumentation has `app.add_middleware(OpenTelemetryMiddleware, ...)`. But we don't really have to call it that.

**Comment by Kludex** [comment]
The asgi and wsgi were merged. Do we need the logging ones as well here?

**Comment by alexmojaki** [comment]
nah
