### ISSUE TITLE
Don't configure automatically

### ISSUE THREAD

**Issue by alexmojaki** [pydantic/logfire#194]
As announced in https://pydanticlogfire.slack.com/archives/C06EDRBSAH3/p1716143149301069, the log/span/instrument methods shouldn't implicitly initialize config. This requires a few steps:

1. Make sure that all docs explicitly call `logfire.configure()` before anything else.
2. https://github.com/pydantic/logfire/issues/193 so that `instument_*` methods can emit a warning if called before configuring. Currently the problem is that users may call e.g. `SQLAlchemyInstrumentor().instrument()` and forget to configure and we can't do anything about that.
3. Emit warnings when calling methods before configure.
4. Stop emitting spans (but keep the warning) when calling methods before configure.

**Comment by bllchmbrs** [comment]
Please!
