### ISSUE TITLE
Live tail in the UI seems to scroll in a strange way

### ISSUE THREAD

**Issue by bllchmbrs** [pydantic/logfire#201]
### Description

So I am in the UI, I know that I've got usage happening BUT I cannot see it.

I've been having issues with the UI in the past week, but today it's gotten really bad.

My experience is:

(1) When the page loads it drops me to 9:38
(2) When I scroll it doesn't seem to scroll, then scrolls to the current time, but then it doesn't STOP scrolling and I end up at 9:20. Other times it just stays at 9:38.
(3) The visibility filter doesn't work (I am trying to change the scope) and services. Not sure why this is the case, it used to work just fine.

**Comment by e-hosseini** [comment]
Thank you for bringing the issue to our attention, @bllchmbrs. It has been resolved. Please don't hesitate to reach out if you encounter any further difficulties.
