### ISSUE TITLE
Can't login - Github org auth fails

### ISSUE THREAD

**Issue by rtspeaks360** [pydantic/logfire#203]
### Description

I can't seem to login. 

My colleague shared a link with me to join an organisation and when I clicked it on it doesn't go past the github auth page.

The platform api call says the orgainisation already exists, and it fails. 

![Screenshot 2024-05-22 at 12 41 28](https://github.com/pydantic/logfire/assets/10489441/ca3ecbe8-03db-4765-83b5-1b2ccf446dab)

Do I need to do something here?

I tried to signup yesterday when the platform was down. Does that has anything to do with this?

**Comment by hramezani** [comment]
Thanks @rtspeaks360 for reporting this issue.

when you login into logfire it creates an organization and user with your GitHub username.
It seems there is already an organization with your GitHub username. So, logfire can't create a new one.

You can change the suggested name in the box(the pic that you attached) and then you will have your organization and will be added to your friend organization.

BTW, we need to improve error handling there as well.

**Comment by e-hosseini** [comment]
The issue has been fixed.
