### ISSUE TITLE
All records just disappeared in the UI

### ISSUE THREAD

**Issue by bllchmbrs** [pydantic/logfire#211]
### Description

have the following error in the console:
`120Error: <rect> attribute width: A negative value is not valid. ("-2.1666666666666665")`

<img width="800" alt="image" src="https://github.com/pydantic/logfire/assets/1642503/5a31bd25-6a55-4113-9de4-dc1dfa71d634">

**Comment by bllchmbrs** [comment]
reported this in slack as well.

I have no query, so this should "just work".

**Comment by alexmojaki** [comment]
I believe this was caused by backend ingest problems at the time. The browser console errors about `<rect>` are old an unrelated.
