### ISSUE TITLE
Show a better warning when ingest fails

### ISSUE THREAD

**Issue by samuelcolvin** [pydantic/logfire#220]
### Description

See [this message on slack](https://pydanticlogfire.slack.com/archives/C06EDRBSAH3/p1717000345491819?thread_ts=1716999128.337239&cid=C06EDRBSAH3) when ingest fails, we should catch the exception and emit an informative warning, so no stacktrace is shown.

**Comment by alexmojaki** [comment]
Done in https://github.com/pydantic/logfire/pull/252
