### ISSUE TITLE
Docs breadcrumbs usually start with 'Intro'

### ISSUE THREAD

**Issue by alexmojaki** [pydantic/logfire#224]
e.g. 'Intro > Legal'. This doesn't make sense.

![Screenshot 2024-05-30 at 14 48 28](https://github.com/pydantic/logfire/assets/3627481/ce155de0-36bc-4956-bead-728661a674ad)

**Comment by Kludex** [comment]
@sydney-runkle @samuelcolvin do we bump mkdocs-material on our private PyPI?

**Comment by sydney-runkle** [comment]
Yeah we should bump it there.

I wouldn't be surprised if this was an issue somewhere in `mkdocs.yml`...

**Comment by sydney-runkle** [comment]
I think it might be bc `Intro` is attached to `index.md`:

https://github.com/pydantic/logfire/blob/2418250cf99ce94f49d873830882777572257c24/mkdocs.yml#L68

**Comment by Kludex** [comment]
- Close this on #240
