### ISSUE TITLE
Change level of Postgres Instrumentation

### ISSUE THREAD

**Issue by bllchmbrs** [pydantic/logfire#226]
### Question

I'm using the postgres instrumentation.

It's quite chatty at the `info` level. Is there a way of lowering this? I took a look at [the instrumentation docs for OpenTelemetry](https://opentelemetry-python-contrib.readthedocs.io/en/latest/instrumentation/psycopg2/psycopg2.html) but I couldn't figure it out/see what I should do.

I'd like to drop it to `debug`

**Comment by adriangb** [comment]
Unfortunately there is nothing built into opentelemetry to lower the level of a group of spans (e.g. from an instrumentation).

I'm not saying it's a good long term solution but you could filter them out via a query filter.

@alexmojaki any ideas for making this part of the SDK? It could alter the level before exporting based on the scope name.

**Comment by bllchmbrs** [comment]
This would be a nice QoL improvement, it's so chatty it immediately overwhelms by logs.

**Comment by bllchmbrs** [comment]
The best practice here is to filter this in the UI either via a otel scope query: `otel_scope_name != 'opentelemetry.instrumentation.psycopg2'` or by clicking visibility and removing the scope.

**Comment by alexmojaki** [comment]
Discussion here: https://pydanticlogfire.slack.com/archives/C06EDRBSAH3/p1717437392293579
