### ISSUE TITLE
Anthropic new release has breaking changes with downstream effects on Logfire's Anthropic support

### ISSUE THREAD

**Issue by willbakst** [pydantic/logfire#227]
### Description

Anthropic pulled tools out of beta, so the beta stuff no longer exists in newer versions of the package. This means that someone using the newest version of their SDK can't use Logfire + Anthropic.

Solution here is to require the use of the most recent package and update dependencies on the old beta types and code to just use the now standard code.

**Comment by willbakst** [comment]
Submitting a PR to fix this shortly.

**Comment by alexmojaki** [comment]
Fixed in https://github.com/pydantic/logfire/pull/249
