### ISSUE TITLE
True / False isn't showing up in the UI

### ISSUE THREAD

**Issue by ShravanSunder** [pydantic/logfire#270]
### Description

True / False isn't showing up in the UI.  I'ved check the logs and its suppose dot be True

![2024-06-18 0649 Brave Browser Live · ShravanSunderaskluna · Pydantic Logfire](https://github.com/pydantic/logfire/assets/5294949/d7e520b9-a8a7-4e59-b0d7-4f9a6bc25aa5)

**Comment by alexmojaki** [comment]
Thanks for the report. Simple repro:

```python
import logfire
logfire.configure()
logfire.info('hi', x=True, y=False)
```

<img width="222" alt="Screenshot 2024-06-19 at 01 07 22" src="https://github.com/pydantic/logfire/assets/3627481/59e21274-1a51-4d90-b64b-609f83f72795">

<img width="222" alt="Screenshot 2024-06-19 at 01 07 30" src="https://github.com/pydantic/logfire/assets/3627481/66e8039c-657c-4177-8fb9-ed8ad00f5d3c">

**Comment by alexmojaki** [comment]
This is fixed, thanks @dmontagu!
