### ISSUE TITLE
Limit decimals in `Requests Average Duration` on the default `Web Server Monitoring Dashboard`

### ISSUE THREAD

**Issue by yury-fedotov** [pydantic/logfire#289]
### Description

This chart contains unnecessary decimals removing which would help reading the value while hovering over bars:

![Screenshot 2024-06-29 at 10 09 00 PM](https://github.com/pydantic/logfire/assets/102987839/813423d4-b739-432d-a408-cf6223f3ddf9)

Apparently functionality to round duration exists in other charts (like below), and I think it can be a good fit here too.

![Screenshot 2024-06-29 at 10 12 34 PM](https://github.com/pydantic/logfire/assets/102987839/2316734e-cc95-413a-9610-6b5ad92ea9a7)

> P.S. I'm very new to observability and used `logfire` for the first time this evening - it's incredible!

**Comment by ChristopherGS** [comment]
@ddanielcruzz looks like this one is fixed
