### ISSUE TITLE
Supported way to check credentials?

### ISSUE THREAD

**Issue by 2e0byo** [pydantic/logfire#299]
### Question

I want to check if logfire is set up properly, and drop it from the logging stack if not.[0] I can achieve this by relying on internal details:

```python
def _logfire_available(token: str) -> bool:
    import logfire
    from logfire.exceptions import LogfireConfigError

    try:
        creds = (
            logfire._internal.config.LogfireConfig()._initialize_credentials_from_token(
                token
            )
        )
    except LogfireConfigError:
        return False
    else:
        return creds.project_name and creds.project_url
```

Is there any supported way to do this?

[0] At the moment we are evaluating logfire, and failure to bring it up should not bring down the stack. This will likely change, but the use case strikes me as not *that* odd. At the moment logfire will call rich.prompt.Prompt (!) if something doesn't work. I'd love not to have to ship rich, but this is beta and we can live with that, but services stalling at a prompt is not going to win the team over.

**Comment by alexmojaki** [comment]
If you set the logfire token with the `LOGFIRE_TOKEN` env var or in `pyproject.toml`, then you can use `logfire.configure(send_to_logfire='if-token-present')`.

I'm not sure how you imagine using your `_logfire_available` function. If you have a non-empty token, don't you expect it to be valid?

**Comment by 2e0byo** [comment]
> If you set the logfire token with the `LOGFIRE_TOKEN` env var or in `pyproject.toml`, then you can use `logfire.configure(send_to_logfire='if-token-present')`.

Ah, that's nice.

> I'm not sure how you're using your `_logfire_available` function. If you have a non-empty token, don't you expect it to be valid?

Not at this stage. Currently I want to catch and log failures to set up experimental services (including logfire). I quite understand that this isn't the usual failure profile: normally you want a service not to run, rather than run without logging.

**Comment by alexmojaki** [comment]
If your token is invalid it'll still log to console. You don't want that?

**Comment by 2e0byo** [comment]
Thanks, `if-token-present` resolves the problem of blocking; setting an invalid token ('foobar') behaves the same as no token. But it doesn't log the fact that no token is present, so the failure is still silent. Is there any supported way to hook into the logic it uses to test the token?

**Comment by alexmojaki** [comment]
```python
import logfire

logfire.configure(token='foobar')
```

gives me `UserWarning: Invalid Logfire token.`

**Comment by 2e0byo** [comment]
thanks! that's it. I'd tried `logfire.configure`, but without passing a token or setting the env var. Good to know it doesn't block when an invalid token is present.

The function I asked for can thus be written as:

```python
def _logfire_available(token: str) -> bool:
    import logfire
    from logfire.exceptions import LogfireConfigError

    try:
         logfire.configure(token)
    except LogfireConfigError:
        return False
```

Which is good enough for what I'm doing.

**Comment by alexmojaki** [comment]
but it doesn't raise an exception, it's a warning

**Comment by 2e0byo** [comment]
it certainly raises for me, with 0.31.0. I'll upgrade and try again.

**Comment by 2e0byo** [comment]
hah, yes, behaviour has changed (I did ofc notice your warning, but didn't think to check the version). I could catch the warning, but that's global state; out of the two I'd rather use an implementation detail.

**Comment by alexmojaki** [comment]
> Good to know it doesn't block when an invalid token is present.

What did you mean by this then?

**Comment by 2e0byo** [comment]
> > Good to know it doesn't block when an invalid token is present.
> 
> What did you mean by this then?

On the face of it `send_to_logfire="if-token-present"` only implies behaviour when 1. no token is present and 2. a valid token is present. I meant that 3. an invalid token is present behaves (surprisingly for me) like 1., not 2. or something else (e.g. prompting). This behaviour was tested on 0.31.0 with an invalid token and the structlog processor, so unless I did something stupid (very possible) the move from exception to warning wasn't responsible. But I'm brand new to logfire, and perhaps I somehow tested invalidly.

I'll PR to the docs to suggest clarifying the meaning of `if-token-present`.

**Comment by alexmojaki** [comment]
This isn't about `if-token-present`. An invalid token doesn't raise an exception. The code in https://github.com/pydantic/logfire/issues/299#issuecomment-2205808009 is complete.

You said "Good to know it doesn't block" but it's not clear to me if you find it good.

**Comment by 2e0byo** [comment]
> This isn't about `if-token-present`. 

Sorry, I didn't scroll up and relied on memory. I was indeed surprised by `if-token-present`; I was also surprised by `.configure` not blocking when an invalid token is passed, since it does block with no token.

> You said "Good to know it doesn't block" but it's not clear to me if you find it good.

Well I'd like some way to hook into the token test, but I can certainly see why this approach was taken.

The nearest thing seems to be:

```python
def valid_token(token: str) -> bool:
    return bool(logfire._internal.config.LogfireConfig()._initialize_credentials_from_token(token))
```

This is beta software and I can't find the request anywhere in the issue tracker. If it isn't supported I'm perfectly happy to go with a hack for now; on my own head be it.

**Comment by 2e0byo** [comment]
On the offchance anyone finds this useful I've ended up enforcing the behaviour I want with a validator and `pydantic-settings`. `if-token-present` removes the need to drop logfire from the stack, which is nice.

```python
from functools import cache
from typing import Annotated
from pydantic import AfterValidator

def validate_logfire_token(token: str) -> str:
    import logfire

    if not logfire._internal.config.LogfireConfig()._initialize_credentials_from_token(
        token
    ):
        raise ValueError("Invalid Token")
    return token

LogfireToken = Annotated[str, AfterValidator(validate_logfire_token)]
```

Whether this makes sense depends heavily on your use case ofc, but it's nice that it's possible
