### ISSUE TITLE
Add the `logfire.instrument_mysql()`

### ISSUE THREAD

**Issue by Kludex** [pydantic/logfire#310]
### Description

OpenTelemetry MySQL Instrumentation[](https://opentelemetry-python-contrib.readthedocs.io/en/latest/instrumentation/mysql/mysql.html#module-opentelemetry.instrumentation.mysql)

**Comment by aditkumar72** [comment]
@Kludex Could you please assign this to me ?

**Comment by Kludex** [comment]
Done @aditkumar72 :)
