### ISSUE TITLE
Can Logfire be used with Prometheus, Jaeger and Grafana?

### ISSUE THREAD

**Issue by gustavosett** [pydantic/logfire#317]
### Question

I read the entire introduction, went through the documentation and looked in the documentation's "search" and I believe I didn't understand how the infrastructure works. Am I doomed to using the pydantic's API to use this open-source tool?

I apologize if this is a misunderstanding...

**Comment by gustavosett** [comment]
This is only a SDK, sorry for my misunderstanding.

**Comment by Kludex** [comment]
Precisando de alguma coisa, só falar. :)

---

If you need anything, just let us know. :)

**Comment by alexmojaki** [comment]
Yes it can, it's just not properly documented. And currently as pointed out in https://github.com/pydantic/logfire/issues/298 you have to authenticate with Logfire even if you don't send data to it.

**Comment by alexmojaki** [comment]
Yes, you can now with the newest release (0.50.0). See https://docs.pydantic.dev/logfire/guides/advanced/alternative_backends/
