### ISSUE TITLE
中文文档上线了 🎉 🎉 🎉 原汁原味的中文

### ISSUE THREAD

**Issue by horizon365** [pydantic/logfire#369]
### Question

中文文档上线了 🎉 🎉 🎉 

原汁原味的中文 https://pydantic.com.cn/logfire/

**Comment by alexmojaki** [comment]
🙏 

👀 

<img width="1639" alt="Screenshot 2024-08-07 at 12 12 19" src="https://github.com/user-attachments/assets/2c506e19-1cd3-4fa5-8a18-d9e0f2324ec8">

**Comment by horizon365** [comment]
> 🙏
> 
> 👀
> <img alt="Screenshot 2024-08-07 at 12 12 19" width="1639" src="https://private-user-images.githubusercontent.com/3627481/355772973-2c506e19-1cd3-4fa5-8a18-d9e0f2324ec8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM0MzQxNDUsIm5iZiI6MTcyMzQzMzg0NSwicGF0aCI6Ii8zNjI3NDgxLzM1NTc3Mjk3My0yYzUwNmUxOS0xY2QzLTRmYTUtOGExOC1kOWUwZjIzMjRlYzgucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgxMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MTJUMDMzNzI1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NmEzOTk2MjliM2FkYmNlNDRjYjA0Mzk1NzkyMzQ3MTU2YWFkM2VhZjIwNzllYTg1MTRmM2Y4NTBmODU4MmZkNCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.KKhqm5Z8CZFI6U6WlfRPOPrcUZOx04cJFyFpPjKeQPQ">

thanks for feedback, i have fix it .
最新访问网址：  https://pydantic.com.cn/logfire/

**Comment by Kludex** [comment]
@horizon365 We saw you doing this for multiple packages. What's the idea?

**Comment by Kludex** [comment]
If there's something we need to do, please let us know @horizon365 :)
