### ISSUE TITLE
Live View - Filters Menu - Long Span names run the menu off screen

### ISSUE THREAD

**Issue by slingshotvfx** [pydantic/logfire#370]
### Description

Long span names (and possibly scopes, etc as well, but I haven't tested) run the menu off the left side of the screen:

![image](https://github.com/user-attachments/assets/b582f608-afbb-46f1-a452-840e734864c6)

### Python, Logfire & OS Versions, related packages (not required)

Windows 10 / Firefox 128.0.3

**Comment by sydney-runkle** [comment]
cc @ddanielcruzz, is this still an issue?

**Comment by alexmojaki** [comment]
Looks fixed, thanks @ddanielcruzz or whoever did this
