### ISSUE TITLE
How to use with FastAPI, SQLModel and Postgres, etc.?

### ISSUE THREAD

**Issue by TheRealBecks** [pydantic/logfire#377]
### Question

I am new to FastAPI and the whole stack, so I'm now trying to set up Logfire. 

I have this example model configured with SQLModel:
https://github.com/TheRealBecks/purple_chili/blob/445fbf195aa9ac189fbcf0541e498d5b9bc511b1/purple_chili/app/models/hero.py#L1-L8

The database connection to Postgres will be created by SQLModel:
https://github.com/TheRealBecks/purple_chili/blob/445fbf195aa9ac189fbcf0541e498d5b9bc511b1/purple_chili/app/core/postgres.py#L1-L11

I then updated my `main.py` file:
```
import logfire
from fastapi import FastAPI

from app.api.routers import api_router
from app.core.postgres import create_db_and_tables
from app.core.settings import settings

create_db_and_tables()

app = FastAPI()

logfire.configure(token=settings.LOGFIRE_TOKEN, pydantic_plugin=logfire.PydanticPlugin(record="all"))
logfire.instrument_fastapi(app)

app.include_router(api_router, prefix=settings.API_V1_STR)
app.include_router(api_router)
```

These packages are already installed:
```
requires-python = "==3.12"
dependencies = [
  "fastapi[standard]==0.112.0",
  "logfire[fastapi,httpx,jinja2,psycopg,requests,sqlalchemy,starlette,system-metrics,urllib,urllib3]==0.50.1",
  "psycopg[binary,pool]==3.2.1",
  "pydantic==2.8.2",
  "pydantic-settings==2.4.0",
  "sqlmodel==0.0.21",
]
```
As you can see I already installed the additional packages for Logfire to get the packages for OTEL.

When I start FastAPI I can see `GET` and `POST` requests in the Logfire live web vview, that's good! 😀

But I thought that I will also see e.g. Postgres data like SQL commands, HTTPX, sqlalchemy and so on.

So I'm not sure if I'm doing to right. I also read the documentation for FastAPI, but I can't find out if I need to install these OTEL packages like I did with the `extras`. Do I need to change something in my `main.py` for the database and so on?

**Comment by alexmojaki** [comment]
Just as you have written `logfire.instrument_fastapi`, also call `logfire.instrument_psycopg(); logfire.instrument_httpx(); logfire.instrument_sqlalchemy()`.

**Comment by alexmojaki** [comment]
(You probably don't need to instrument both sqlalchemy and psycopg, but you can try with both and see what happens)

**Comment by TheRealBecks** [comment]
@alexmojaki Thank you for your fast answer!

While writing the answer that it's still not working it came into my mind that the order matters and that I need to call `logfire` first before I call `create_db_and_tables`. I can now see `psycopg` information in the live view. It's now working this way:
```
import logfire
from fastapi import FastAPI

from app.api.routers import api_router
from app.core.postgres import create_db_and_tables
from app.core.settings import settings

logfire.configure(token=settings.LOGFIRE_TOKEN, pydantic_plugin=logfire.PydanticPlugin(record="all"))
logfire.instrument_psycopg()
logfire.instrument_httpx()
logfire.instrument_sqlalchemy()

create_db_and_tables()

app = FastAPI()
logfire.instrument_fastapi(app)

app.include_router(api_router, prefix=settings.API_V1_STR)
app.include_router(api_router)
```

That brings up even more questions:
In the file `app.core.settings` I already create a `settings` object from a class that bases on the Pydantic class `BaseSettings`, but is that a problem for logfire? Can it still get all Pydantic information it needs?

**Comment by alexmojaki** [comment]
See the first section of https://docs.pydantic.dev/logfire/integrations/pydantic/, particularly the last sentence:

> Note that if you only use the last option then only models defined and imported after calling logfire.configure will be instrumented.
