### ISSUE TITLE
Would be good for cancel filter button

### ISSUE THREAD

**Issue by ShravanSunder** [pydantic/logfire#380]
### Description

![2024-08-16 0826 Brave Browser Perplexity](https://github.com/user-attachments/assets/24f09d54-753e-407d-b3c7-998600e69a1b)

Would be good to easily cancel a filter.  (an x button in the serach bar)

**Comment by summerscope** [comment]
This feature has been implemented, so I'm going to close this one @ShravanSunder 
<img width="1257" alt="Screenshot 2024-11-06 at 12 27 46" src="https://github.com/user-attachments/assets/aeb70ff4-252f-4c9c-944d-114f16d1308c">

_(NB we are making further improvements to the live view querying and you can expect to see those soon)_
