### ISSUE TITLE
Psyopg2 Instrumentation doesn't work with `RealDictCursor`

### ISSUE THREAD

**Issue by bllchmbrs** [pydantic/logfire#381]
### Description

I'm still trying to get the exact repro, but I cannot instrument psycopg2 and get results when I use `from psycopg2.extras import RealDictCursor`

I am using the instrumentation, BUT when I go to run it, no values show up for cursors that go through that path.

```python
import logfire
import psycopg2 as pg
from psycopg2.extras import RealDictCursor

logfire.instrument_psycopg()

conn = pg.connect()

def get_plain_cursor(conn):
    return conn.cursor()

def get_cursor(conn):
    return conn.cursor(cursor_factory=RealDictCursor)


def run_query(cur, query: str, args=None):
    try:
        if isinstance(args, tuple):
            cur.execute(query, args)
        elif isinstance(args, list):
            cur.executemany(query, args)
        else:
            cur.execute(query)
    except Exception as e:
        logger.error("Failed to run query", error=e)
        raise e

with get_plain_cursor(conn) as pc:
    run_query(pc, "SELECT 1")
# this shows the select query in logfire

with get_cursor(conn) as pc:
    run_query(pc, "SELECT 1")
# this does NOT show the select query
```

**Comment by Kludex** [comment]
Hey @bllchmbrs,

Sorry for the late reply here.

It seems this is an issue with OpenTelemetry itself: https://github.com/open-telemetry/opentelemetry-python-contrib/issues/578

I'll see if I can open a PR on their side, but for the time being, you can move the `cursor_factory` parameter up to the `connect(cursor_factory=...)` and remove it from the `cursor`, as per [this comment](https://github.com/open-telemetry/opentelemetry-python-contrib/issues/578#issuecomment-1100904634).

**Comment by Kludex** [comment]
I tried a bit, but that code source is giving me a hard time. I'll close this as it's really an OpenTelemetry issue, as per last message.

But I'll try to get back to it when my PRs about improving type hint on their side are merged, specifically this one: https://github.com/open-telemetry/opentelemetry-python-contrib/pull/3068

**Comment by Kludex** [comment]
Let me know if you can use the workaround mentioned here:

> I'll see if I can open a PR on their side, but for the time being, you can move the cursor_factory parameter up to the connect(cursor_factory=...) and remove it from the cursor, as per https://github.com/open-telemetry/opentelemetry-python-contrib/issues/578#issuecomment-1100904634.
