### ISSUE TITLE
How can get alert(email notification) when error appear

### ISSUE THREAD

**Issue by wogno** [pydantic/logfire#391]
### Question

Hi, I use  logfire in project in production, I really like it, but I don't get notifcation when error appear, so it's a little bite difficult to always look to see if that has error or not.

**Comment by Kludex** [comment]
I'll be working on this on the next week. I'll give updates.

**Comment by wogno** [comment]
Ok thanks, so waiting

**Comment by sydney-runkle** [comment]
@Kludex, update here?

**Comment by Kludex** [comment]
@dmontagu Is working on alerts. He'll post an estimation here in a few hours.

**Comment by Kludex** [comment]
This is duplicated of https://github.com/pydantic/logfire/issues/80.

Please follow that issue instead.
