### ISSUE TITLE
Export data to third-party tool

### ISSUE THREAD

**Issue by alessandrofacchin** [pydantic/logfire#403]
### Question

Does Logfire implement any API to systematically export data to third-party tools such as Grafana or Cloud Logging?

**Comment by alexmojaki** [comment]
To clarify, do you want to initially send data from the client SDK to Grafana, or do you want to copy old data that's already sitting in the Logfire database?

**Comment by Kludex** [comment]
@alessandrofacchin Could you clarify? We want to understand your request, so we can provide the best solution. :)

**Comment by alessandrofacchin** [comment]
I would like to be able to leverage the rich information extracted through Logfire in my existing Grafana project, in order to integrate it with my existing monitoring tools (i.e. k8s monitoring, db monitoring, etc.).

I believe some options could be:
- to implement a Logfire Data Source Plugin in Grafana;
- to send data from Logfire through Prometheus using Pushgateway;
- to expose a webhook in Grafana and to configure Logfire to send new logs to such webhook (https://grafana.com/developers/plugin-tools/tutorials/).

What do you think?

**Comment by CharlesFarhat** [comment]
I am also interested to be able to send my logfire span to graphana, how could I manage that ?

**Comment by alexmojaki** [comment]
See https://logfire.pydantic.dev/docs/guides/advanced/alternative_backends/

**Comment by CharlesFarhat** [comment]
yeah... I found it later on :) Sorry to bother i forget to delete my post... Thanks a lot for your reactivity !

**Comment by Kludex** [comment]
We good here? Is the last link Alex provided clear? @alessandrofacchin

**Comment by alessandrofacchin** [comment]
Perfect yes, thanks! 🙌🏼
