### ISSUE TITLE
Inconsistent spelling: "Organisation" vs. "Organization" in invitation modal

### ISSUE THREAD

**Issue by alejsdev** [pydantic/logfire#417]
**Description:**

There is an inconsistent use of "organization" (US English) and "organisation" (UK English) in the modal for generating invitation links. Since US English spelling is predominantly used throughout the rest of the application, it seems the inconsistency is unintentional. 

**Steps to reproduce:**

1. Create a new organization.
2. Navigate to _settings/members/invitations_
3. Click the **New Invitation Link** button to open the invitation modal.
4. In the modal, you can see the use of "Organisation" (with an "s") in the title, while "Organization" (with a "z") is used in the body text.

![image](https://github.com/user-attachments/assets/4f8c30fe-7e59-4437-9872-af8f91ee88da)

**Comment by alexmojaki** [comment]
cc @ddanielcruzz @e-hosseini

**Comment by Kludex** [comment]
We should use "organization".

**Comment by Kludex** [comment]
Thanks @alejsdev :)

I've fixed it on our frontend, it should be available on our next release. :)

I'll close this preemptively.
