### ISSUE TITLE
don't require a module in `@logfire.instrument` if a name is explicitly provided.

### ISSUE THREAD

**Issue by strangemonad** [pydantic/logfire#422]
### Description

The internals of `@logfire.instrument` assert that `inspect.getmodule(func.__code__) is not None`. There's a context that I'm running in (an industrial automation controller)  that dynamically executes a python code file in a way that doesn't set any top-level module.

**Comment by alexmojaki** [comment]
Fixed, see https://github.com/pydantic/logfire/releases/tag/v2.0.0
