### ISSUE TITLE
Spans overlap

### ISSUE THREAD

**Issue by keyboardAnt** [pydantic/logfire#437]
### Description

Different runs (namely, executions) of the following code generate span logs that the UI presents under the same span.
```python
random.seed(0)

with logfire.span("Run with args:\n{args}\nat {ts}", args=locals(), ts=time.time()):
    # my code
```

**Comment by alexmojaki** [comment]
Trace and span IDs are generated by `opentelemetry.sdk.trace.id_generator.RandomIdGenerator` by default. Based on https://github.com/open-telemetry/opentelemetry-python/issues/2974, this is intended behaviour for testing purposes.

Do you need different behaviour? Are you using logfire to instrument tests, and those tests use `random.seed`?

Amusingly, `logfire` contains a workaround called `SeededRandomIdGenerator`, you just need to pass `None` (allowed despite what the type hint says) to use a random seed:

```python
import random

random.seed(0)

import logfire
from logfire.testing import SeededRandomIdGenerator

logfire.configure(id_generator=SeededRandomIdGenerator(None))

with logfire.span('foo'):
    logfire.info('s')
```

**Comment by keyboardAnt** [comment]
Thanks @alexmojaki
