### ISSUE TITLE
Test Python 3.13 in CI

### ISSUE THREAD

**Issue by alexmojaki** [pydantic/logfire#471]

**Comment by sydney-runkle** [comment]
I think this might be blocked by https://github.com/indygreg/python-build-standalone/issues/263 for now, but I'm digging into this more.

**Comment by alexmojaki** [comment]
@Kludex you asked about switching from rye to uv, maybe this is good motivation?

**Comment by alexmojaki** [comment]
This is primarily blocked on https://github.com/open-telemetry/opentelemetry-python/pull/4067 and https://github.com/open-telemetry/opentelemetry-python-contrib/pull/2724
