### ISSUE TITLE
Django instrumentation silently doesn't work for ASGI requests

### ISSUE THREAD

**Issue by alexmojaki** [pydantic/logfire#472]
A user couldn't get the Django instrumentation working (https://pydanticlogfire.slack.com/archives/C06EDRBSAH3/p1722460460137619?thread_ts=1722440635.372479&cid=C06EDRBSAH3). With difficulty we realised that it was because they were using ASGI. In `opentelemetry/instrumentation/django/middleware/otel_middleware.py` you can see that ASGI requests are silently ignored when `opentelemetry-instrumentation-asgi` isn't installed.

Firstly, we should document this loudly.

Then for people who miss this point, we should either:

1. Try to detect ASGI requests and warn the user if needed. Not sure how easy this is.
2. Add a mandatory `is_asgi` parameter to `instrument_django` to force the user to tell us the situation, then raise an error if needed.
3. Always install `opentelemetry-instrumentation-asgi` with the `django` extra.
4. Remove the `django` extra and replace it with `django-wsgi` and `django-asgi`.

@samuelcolvin what do you think?

**Comment by Kludex** [comment]
> Remove the django extra and replace it with django-wsgi and django-asgi.

We can also just add `django-async`.

**Comment by Kludex** [comment]
The first step here is to document this.

**Comment by alexmojaki** [comment]
> > Remove the django extra and replace it with django-wsgi and django-asgi.
> 
> We can also just add `django-async`.

The idea is that the user has to be aware of the distinction and make an explicit choice. If they don't check docs carefully they may easily think that `pip install logfire[django]` should just work, they won't get an error at any point.

**Comment by Kludex** [comment]
The easiest here is to add `opentelemetry-instrumentation-asgi` to the `django` extras...

**Comment by Kludex** [comment]
In the meantime, while we don't solve this... I've added a note to the docs: https://github.com/pydantic/logfire/pull/630

**Comment by Kludex** [comment]
We now have a note on the top of the Django page about this:

<img width="742" alt="Screenshot 2024-11-28 at 12 48 48" src="https://github.com/user-attachments/assets/003a2bf0-2107-489a-8058-915089ada408">
