### ISSUE TITLE
Is there a way to add tags to a span after it is created?

### ISSUE THREAD

**Issue by ohmeow** [pydantic/logfire#477]
### Question

I have additional tags I want to that come from the result of a function running inside a span, but I'm not able to add them via `span.tags += ["my_tag"]` with the current API.

Is there some other way to do this?

Thanks!

**Comment by alexmojaki** [comment]
```python
import logfire

logfire.configure()

with logfire.span('my_span', _tags=['foo', 'bar']) as span:
    span._span.set_attribute('logfire.tags', span.tags + ('baz', 'qux'))
```

We can certainly make this easier.

**Comment by AdolfoVillalobos** [comment]
Hi! @alexmojaki 

I would love to work on this.  I thought about two approaches.

I would appreciate guidance on the best approach to the project vision and design principles.

## 1. create `add_tags`method

The implementation would be something like:

```python
class LogfireSpan(ReadableSpan):
    # ... 

    def add_tags(self, *tags: str) -> None:
        """Add tags to the span."""
        with handle_internal_errors():
            if self._span is None:
                self._otlp_attributes.setdefault(ATTRIBUTES_TAGS_KEY, []).extend(tags)
            else:
                existing_tags = self._span.attributes.get(ATTRIBUTES_TAGS_KEY, [])
                new_tags = uniquify_sequence(existing_tags + list(tags))
                self._span.set_attribute(ATTRIBUTES_TAGS_KEY, new_tags)

    # ... 

```

Then calls would be:
```python
with logfire.span("my_span") as span:
    span.add_tags("tag1", "tag2", "tag3")
```

## 2. add a setter to the `tags`property

This would give us even more control over the tags:

```python
class LogfireSpan(ReadableSpan):
    # ... 

    @property
    def tags(self) -> Sequence[str]:
        return self._get_attribute(ATTRIBUTES_TAGS_KEY, [])

    @tags.setter
    @handle_internal_errors()
    def tags(self, new_tags: Sequence[str]) -> None:
        """Set or add tags to the span."""
        existing_tags = self.tags
        updated_tags = uniquify_sequence(existing_tags + list(new_tags))
        if self._span is None:
            self._otlp_attributes[ATTRIBUTES_TAGS_KEY] = updated_tags
        else:
            self._span.set_attribute(ATTRIBUTES_TAGS_KEY, updated_tags)

    # ... 
```

Then we would have a much more flexible approach, as we would leverage the features from python's list type:

```python
with logfire.span("my_span") as span:
    span.tags = ["tag1", "tag2"]
    # add more tags:
    span.tags = span.tags + ["tag3", "tag4"]
    # Delete tags
    span.tags = []
  ```
  
  
  ----
  
  There may be even a better way. I'm open to suggestions :)

**Comment by alexmojaki** [comment]
Thanks @AdolfoVillalobos for offering to contribute! I think a property setter would be best. But we should make sure it consistently stores and returns a tuple. Right now `span.tags` returns either an empty list or nonempty tuple which means `span.tags += [...]` would inconsistently raise a TypeError. And if we used lists instead of tuples then users might try `span.tags.append(...)`.

**Comment by alexmojaki** [comment]
Done in #497 thanks to @AdolfoVillalobos, will be in the next release.

**Comment by AdolfoVillalobos** [comment]
> Done in #497 thanks to @AdolfoVillalobos, will be in the next release.

I'm glad to help!. Thank you for your patience and feedback! I have learned a lot and will continue to contribute whenever possible. Cheers!

**Comment by ohmeow** [comment]
awesome. thanks for the addition!
