### ISSUE TITLE
Logging to multiple logfire project simultaneously

### ISSUE THREAD

**Issue by Mumbawa** [pydantic/logfire#493]
### Question

Is there any mechanism to perform logging to multiple logfire project simultaneously from the same app?

To give you an example:

I have a backend service and I have an associated logfire project to this backend (my_backend_logfire_proj)... 

But for whatever reason I also want to log certain specifics events that occur in the same backend to a different logfire project.

**Comment by alexmojaki** [comment]
Duplicate of https://github.com/pydantic/logfire/issues/195

**Comment by alexmojaki** [comment]
@Mumbawa you can now do this using `logfire.configure(local=True)`: https://logfire.pydantic.dev/docs/reference/api/logfire/#logfire.configure(local)

**Comment by Mumbawa** [comment]
Thank you!
