### ISSUE TITLE
Doc: add installation with uv

### ISSUE THREAD

**Issue by sylvainmouquet** [pydantic/logfire#526]
### Description

Hello,

When i need to install logfire with fastapi, the error message is :
```
RuntimeError: The `logfire.instrument_fastapi()` requires the `opentelemetry-instrumentation-fastapi` package.
You can install this with:
    pip install 'logfire[fastapi]'
```

it could be great to add the uv command in the helper : `uv add logfire\[fastapi\]`

**Comment by alexmojaki** [comment]
`uv add 'logfire[fastapi]'` should work too.

**Comment by jules-ch** [comment]
I don't think recommending a specific installer is relevant when raising the error. Hinting with pip is helpful enough.

**Comment by alexmojaki** [comment]
Thanks @jules-ch, I agree.

**Comment by sylvainmouquet** [comment]
Super :thumbsup:
