### ISSUE TITLE
Feature Request: Handle Tool Call Assistant Messages For OpenAI (and other providers)

### ISSUE THREAD

**Issue by willbakst** [pydantic/logfire#54]
Hi! I noticed when using tool calls (function calling) that I get an empty assistant message in the UI (because there's no content, just tool calls). See below:

![April 30 Screenshot from Pydantic Logfire](https://github.com/pydantic/logfire/assets/99370834/502c3d63-ea78-4284-a12c-b6acf49fe5ca)

Would be awesome if this rendered something like a pretty JSON object so it's not empty and I don't have to scroll down to the original response to find the data.

**Comment by Kludex** [comment]
@willbakst Do you have a code snippet for me to reproduce this?

**Comment by willbakst** [comment]
I've confirmed this is working with OpenAI (as well as other providers through Mirascope).

Here is a Mirascope snippet that works with Logfire and the new function calling UI:

```python
from typing import Literal, Type

import logfire
from pydantic import BaseModel

from mirascope.logfire import with_logfire
from mirascope.openai import OpenAIExtractor

logfire.configure()


class TaskDetails(BaseModel):
    description: str
    due_date: str
    priority: Literal["low", "normal", "high"]


@with_logfire
class TaskExtractor(OpenAIExtractor[TaskDetails]):
    extract_schema: Type[TaskDetails] = TaskDetails
    prompt_template = """
    Extract the task details from the following task:
    {task}
    """

    task: str


task = "Submit quarterly report by next Friday. Task is high priority."
task_details = TaskExtractor(
    task=task
).extract()  # this will be logged automatically with logfire
assert isinstance(task_details, TaskDetails)
print(task_details)
```
