### ISSUE TITLE
Am I forced to authenticate manually on local environment?

### ISSUE THREAD

**Issue by ddahan** [pydantic/logfire#541]
### Question

Hi there, 

In a FastAPI Project, I'd like to avoid authenticating manually with `logfire auth` command, even on local environment.

I configured my project this way:

**Settings**
```python
class Settings(BaseSettings):
    LOGFIRE_SEND_TO_LOGFIRE: bool
    LOGFIRE_TOKEN: str | None = None

    model_config = SettingsConfigDict(
        env_file=BASE_DIR / ".env",
        env_ignore_empty=True,
        env_prefix="FAPI_",
        case_sensitive=True,
        extra="forbid",
    )
```

**.env file**
```
FAPI_LOGFIRE_SEND_TO_LOGFIRE=true
FAPI_LOGFIRE_TOKEN=<my-real-write-token>
```

**main.py file**
```python
app = FastAPI(..)
if settings.LOGFIRE_SEND_TO_LOGFIRE:
    logfire.configure(send_to_logfire=True)
    logger.configure(handlers=[logfire.loguru_handler()])
    logfire.instrument_fastapi(app)
```

No matter what I tried, When running `fastapi dev` I get a `LogfireConfigError: You are not authenticated. Please run 'logfire auth' to authenticate.` error.

But in the [documentation](https://logfire.pydantic.dev/docs/#instrument), it seems I should be able to authenticate via token, event during development.

What am I missing here? Thanks

**Comment by Kludex** [comment]
You need to either pass the token via `logfire.configure(settings.LOGFIRE_TOKEN)`, or change the environment variable from `FAPI_LOGFIRE_TOKEN` to `LOGFIRE_TOKEN`.

**Comment by ddahan** [comment]
Thanks for the answer!

> pass the token via logfire.configure(token=settings.LOGFIRE_TOKEN)

Works 👌🏻 thank you!

> change the environment variable from FAPI_LOGFIRE_TOKEN to LOGFIRE_TOKEN

I'd prefer not, as `FAPI` is my env prefix for Pydantic-settings (which is a good practice to have IMO).
