### ISSUE TITLE
Can sign up for Pro

### ISSUE THREAD

**Issue by jessereich-mcs** [pydantic/logfire#549]
### Question

I enter my credit card but it just says saving. I tried last week and now this week with the same results. 

![image](https://github.com/user-attachments/assets/c8cfcca3-1daa-4590-86a9-26669fe79515)

**Comment by jessereich-mcs** [comment]
Oh I just inspected and it looks like my card is being declined (not sure why but I'll investigate). You may want to handle this better on the frontend.

![image](https://github.com/user-attachments/assets/72c7a9fd-c01c-41e2-957a-d842df25e8fe)

**Comment by e-hosseini** [comment]
Hi @jessereich-mcs ,
Thank you for reporting the issue. 
I am working on this case right now and will keep you posted.
Can you try with another card card? 
Feel free to message me on Slack if you need direct communication.

**Comment by jessereich-mcs** [comment]
The other card did work. Are you able to provide any more details about why the first card (Mastercard ending in 8345) was declined?

**Comment by ChristopherGS** [comment]
> The other card did work. Are you able to provide any more details about why the first card (Mastercard ending in 8345) was declined?

@jessereich-mcs we can see in our stripe events that the first card was declined with: `try_again_later` which unfortunately seems to be stripe's code for `we don't know what happened` because it was on the card issuer side: https://docs.stripe.com/declines/codes?locale=en-GB

**Comment by jessereich-mcs** [comment]
Thanks... turns out capital one closed the account because we didn't respond to a notification that we never received 😠 . But thank you for the info.

**Comment by ChristopherGS** [comment]
> Thanks... turns out capital one closed the account because we didn't respond to a notification that we never received 😠 . But thank you for the info.

Thanks for letting us know - we were reasonably confident, but with payments stuff one is always paranoid so we appreciate you telling us this!
