### ISSUE TITLE
Daily CI with unpinned deps

### ISSUE THREAD

**Issue by alexmojaki** [pydantic/logfire#580]
Following up on https://github.com/pydantic/logfire/pull/576

At the bare minimum we need a job that runs daily with the latest versions of all dependencies so that we can detect breakages.

Previously regular CI ran with unpinned dependencies which forced us to fix the problem ASAP. That had downsides, but I want to keep the upsides. I want to have some kind of system so that when the job fails we treat it with similar urgency to before, so that new users aren't immediately faced with a critical error caused by an outstanding bug. Relevant developers should definitely get an email about the job failing, but that's not quite enough. I may miss the email in a sea of notifications, or I may think someone else will deal with it. For now let's just say that if any of us see that CI has failed we should open an urgent issue if there isn't one already, and check with the team what the plan is.

**Comment by Kludex** [comment]
We can also add a weekly dependabot job?

**Comment by Kludex** [comment]
Daily also works (the previous PR is closed).

**Comment by alexmojaki** [comment]
That also works, but I also want daily CI for other things like testing a wider variety of versions as in https://github.com/pydantic/logfire/issues/507 without slowing down PRs.

**Comment by Kludex** [comment]
I forgot that `uv.lock` doesn't seem supported by dependabot yet.

**Comment by alexmojaki** [comment]
Reopening because based on https://github.com/orgs/community/discussions/25351 the current workflow will only send an email to a single person, which isn't loud enough.

**Comment by alexmojaki** [comment]
(I know there's a TODO in that file in the PR which is probably because of this, I hadn't noticed until merging)
