### ISSUE TITLE
Extra message displayed in `openai` instrumentation

### ISSUE THREAD

**Issue by zzstoatzz** [pydantic/logfire#59]
### Description

first off, really excited about `logfire`! 👏 

---

this issue is purely cosmetic and **disclaimer** I could be confused about the expected behavior but I seem to consistently get an extra message displayed in the human readable trace details.

Maybe this is meant to be a placeholder for the `Assistant` response?

![Screenshot 2024-04-30 at 7 22 30 PM](https://github.com/pydantic/logfire/assets/31014960/15370dfa-0173-417b-955e-67d4a670004f)

however the messages in the arguments section agrees with my expectations

![image](https://github.com/pydantic/logfire/assets/31014960/d9df133a-38c9-48d2-a61e-eafb7fa2a1ae)

**Comment by samuelcolvin** [comment]
Yup, we're working on making these panels more configurable/powerful.

**Comment by zzstoatzz** [comment]
closing as im realizing this is a functional dupe of #54
