### ISSUE TITLE
Failed span runs forever in UI

### ISSUE THREAD

**Issue by tonybaloney** [pydantic/logfire#61]
### Description

Even though this span failed because of an exception, in the UI it shows as "ongoing" for over an hour. The process isn't even running anymore. This persists after refreshing as well. 

<img width="831" alt="screenshot 2024-05-01 at 16 45 12" src="https://github.com/pydantic/logfire/assets/1532417/9129e974-ee61-41ab-8a2f-855cf8e18a8d">

**Comment by samuelcolvin** [comment]
Thanks for reporting.

Any chance you could share your code with us?

Do you happen to have a generator with a `break`? I've seen similar things with `GeneratorExit`.

**Comment by tonybaloney** [comment]
It happened in the same span as the crash I reported in #62 so maybe that'll be reproducible? 

<img width="795" alt="screenshot 2024-05-01 at 18 10 01" src="https://github.com/pydantic/logfire/assets/1532417/965a57c3-b9f5-49ff-aa52-1a5e7ba6364d">

Here's the code I used https://github.com/tonybaloney/azure-search-openai-demo/commit/a17664de8da7e96b484b84b22dd6db477eb77cb0

**Comment by samuelcolvin** [comment]
I've seen something similar with OpenAI where I was `break`ing out of a generator response. I'm sure we can come up with a minimal reproduction and then fix.

Some background:

By default open telemetry only sends data about spans when they close, that makes sense in some scenarios, but it means you can't see anything until a span closes, which is obviously not great, when:
1. you're watching your application live
2. spans take more than about a second

So we spend a "start span" - basically a zero duration span at the start of each span so we can show it in the UI almost instantly. Then when the span finishes we send a span as usual that wraps the code in question.

What's happening here is that the start span is sent, but somehow the end/standard span is never sent.

What's weird is that `AttributeError` you reported in #62 should not be a problem.

**Comment by alexmojaki** [comment]
The UI now handles this better.
