### ISSUE TITLE
Support opentelemetry-instrumentation-llamaindex

### ISSUE THREAD

**Issue by yanqianglu** [pydantic/logfire#614]
### Description

Hi,

There is a package to auto-instrument llmaindex `opentelemetry-instrumentation-llamaindex` , I wonder if that can be added to logfire. I tried to use it directly `LlamaIndexInstrumentor().instrument()`, but got `maximum recursion depth exceeded` error when adding it. 

Best,

**Comment by alexmojaki** [comment]
This doesn't seem to be a logfire-specific problem, I can't see how to get `import opentelemetry.instrumentation.llamaindex` to work. It works sometimes with pydantic v2 but I don't think llama-index actually supports that.

**Comment by Kludex** [comment]
@yanqianglu I'll close this issue given Alex comment above.

If you have the availability, please give us an MRE so we can try to play with it. Assuming that it works without Logfire.

Happy new year! :)

**Comment by alexmojaki** [comment]
It looks like I was wrong about llama-index not supporting pydantic v2. So I think that's what you have to use.
