### ISSUE TITLE
FastAPI arguments: Can values in the logs be displayed according to the response_model?

### ISSUE THREAD

**Issue by tomasemilio** [pydantic/logfire#654]
### Question

My FastAPI setup usually follows this pattern: 
1. UserIn: This is a pydantic model (let's say we are creating a user)
2. User: SQLAlchemy model, this is the actual model in the database
3. UserOut: pydantic model, and i specify in the ht route definition @app.route (....... response_model=UserOut).

In this example, I don't show any password, and I only fetch the attributes needed for the response. I would prefer not having to transform User to UserOut too early, but in the logs I see the raw User object, not the UserOut object.

Just to give you an example:
```python
class Base(AsyncAttrs, DeclarativeBase):
    __abstract__ = True
    id: Mapped[UUID] = mapped_column(
        primary_key=True, default=lambda: uuid4(), sort_order=-3
    )
    created_at: Mapped[datetime] = mapped_column(
        default=lambda: datetime.now(UTC),
        nullable=False,
        sort_order=-2,
        type_=TIMESTAMP(timezone=True),
    )
    updated_at: Mapped[datetime] = mapped_column(
        default=lambda: datetime.now(UTC),
        onupdate=lambda: datetime.now(UTC),
        nullable=False,
        sort_order=-1,
        type_=TIMESTAMP(timezone=True),
    )

```
```python
class User(Base):
    __tablename__ = "user"
    name: Mapped[str] = mapped_column()
    email: Mapped[str] = mapped_column(unique=True)
    _password: Mapped[str] = mapped_column(name="password")
    verified: Mapped[bool] = mapped_column(default=False)
    scope: Mapped[list[Role]] = mapped_column(JSON, nullable=False, default=[Role.USER])
    posts: Mapped[list[Post]] = relationship(
        back_populates="user", lazy="select", cascade="all, delete-orphan"
    )
    tags: Mapped[list[Tag]] = relationship(
        back_populates="user", lazy="select", cascade="all, delete-orphan"
    )
    @property
    def password(self) -> str:
        return self._password

    @password.setter
    def password(self, password: str) -> None:
        self._password = get_hash(password)

    def check_password(self, password: str) -> bool:
        return check_hash(password, self.password)

```

and the pydantic models
```python
class BaseOut(BaseModel):
    model_config: ClassVar[ConfigDict] = ConfigDict(from_attributes=True)
    id: UUID
    created_at: datetime
    updated_at: datetime

```

```python
class UserOut(BaseOut):
    name: str
    email: EmailStr
    verified: bool
    scope: list[Role]

```

**Comment by alexmojaki** [comment]
The `FastAPI arguments` span shows the input arguments. It sounds like you want to log the response, which doesn't happen automatically. If you want to change how the input arguments are displayed, then try using the `request_attributes_mapper` argument, see https://logfire.pydantic.dev/docs/integrations/fastapi/#endpoint-arguments-and-validation-errors.

**Comment by tomasemilio** [comment]
Thank you Alex for your response. I know what is going on. I have a dependency injection to load user. and this logic happens inside the dependency definition, This is why the user is displayed in the values. When you have it as a dependency it logs the entire dependency.

**Comment by tomasemilio** [comment]
I understand. The tricky thing is that sometimes, and following the example above, we have these dependencies but the "raw" argument passed to the endpoint is `id_` not the user. It would be great to have the raw arguments be detected, and somehow have logfire understand the nested dependencies.

**Comment by alexmojaki** [comment]
I see two possibilities on your end:

1. Change the raw `user_id: UUID` argument to `user: User` with a dependency, and replace `user_id` with `user.id` in the body.
2. Make `load_user` log the `User` object before returning it.
