### ISSUE TITLE
Add support for Faststream

### ISSUE THREAD

**Issue by rishabhc32** [pydantic/logfire#667]
### Description

Logfire has already built in integrations with Airflow and Celery. It would be great if support for [Faststream](https://faststream.airt.ai/latest/getting-started/) can be added.

**Comment by Kludex** [comment]
Doesn't FastStream has opentelemetry support already? Should work out of the box.

I'm going to try it tomorrow.

**Comment by rishabhc32** [comment]
@Kludex Yeah it does. https://faststream.airt.ai/latest/getting-started/opentelemetry/

Not sure how to integrate it with logfire.

**Comment by Kludex** [comment]
> @Kludex Yeah it does. [faststream.airt.ai/latest/getting-started/opentelemetry](https://faststream.airt.ai/latest/getting-started/opentelemetry/)
> 
> Not sure how to integrate it with logfire.

You just need to run `logfire.configure()`, and it should work as expected.

```py
from faststream import FastStream
from faststream.redis import RedisBroker
from faststream.redis.opentelemetry import RedisTelemetryMiddleware

import logfire

logfire.configure(service_name='faststream')  # Just add this line!

broker = RedisBroker(middlewares=(RedisTelemetryMiddleware(),))

app = FastStream(broker)


@broker.subscriber("test-channel")
async def handle():
    await broker.publish("Hi!", channel="another-channel")


@broker.subscriber("another-channel")
async def handle_next(msg: str):
    assert msg == "Hi!"


@app.after_startup
async def test():
    await broker.publish("", channel="test-channel")
```

See the UI:

<img width="883" alt="Screenshot 2024-12-16 at 13 07 10" src="https://github.com/user-attachments/assets/278c72aa-9b7e-4cc0-9bbd-04483ed8b74c" />

**Comment by rishabhc32** [comment]
Hi @Kludex 

Thanks for the help. It works great!

I just wanted to add(for people stumbling on this issue) that by default faststream sets `instrumenting_module_name` to `faststream.opentelemetry.middleware`.

To override it you can do the following:
```python
@dataclass
class _FaststreamTraceProvider(TracerProvider):
    trace_provider: TracerProvider
    instrumenting_module_name: str = "opentelemetry.instrumentation.faststream"

    def get_tracer(self, instrumenting_module_name: str, *args, **kwargs) -> Tracer:
        return self.trace_provider.get_tracer(self.instrumenting_module_name, *args, **kwargs)

def faststream_configure_logfire(logfire_instance: Logfire):
   broker.add_middleware(
        RabbitTelemetryMiddleware(
            tracer_provider=_FaststreamTraceProvider(
                logfire_instance.config.get_tracer_provider()
            )
        )
    )

```

**Comment by Kludex** [comment]
Can you open an issue on their side? It would be nice to have it fixed on their code. 🤔

**Comment by rishabhc32** [comment]
> Can you open an issue on their side? It would be nice to have it fixed on their code. 🤔

Yeah, would do that.

**Comment by rishabhc32** [comment]
> Can you open an issue on their side? It would be nice to have it fixed on their code. 🤔

@Kludex It was fixed from their side in this PR https://github.com/airtai/faststream/pull/1996
