### ISSUE TITLE
Not available alert

### ISSUE THREAD

**Issue by wogno** [pydantic/logfire#677]
### Description

Base on user of solution(or baser on each specific time), it's possible to detect when solution go down and us alert

**Comment by Kludex** [comment]
Hi @wogno ,

Sorry for the delay here!

Currently, we don't have a real "uptime" service where we call your service via HTTP call or something like that. But I've [created this PR](https://github.com/pydantic/logfire/pull/724) where I explain how to create the kind of alert you want.

I'm waiting for it to be reviewed so it can be added to our documentation, but you can already check it.

Let me know if that would satisfy you. :)
