### ISSUE TITLE
How to integrate logfire system-metrics with prometheus-fastapi-instrumentator

### ISSUE THREAD

**Issue by cyberksh** [pydantic/logfire#693]
### Question

Is there a way I can integrate the logfire system metrics and expose them to the /metrics endpoint? I'm using the below package to auto export API metrics.
 
https://github.com/trallnag/prometheus-fastapi-instrumentator

**Comment by alexmojaki** [comment]
Are you asking how to send the prometheus metrics to the Logfire backend?

**Comment by cyberksh** [comment]
> Are you asking how to send the prometheus metrics to the Logfire backend?

Actually https://github.com/trallnag/prometheus-fastapi-instrumentator exposes some FastAPI metrics on the `/metrics` endpoint of the app.

If I use `logfire.instrument_system_metrics()` in my code, I don't see those metrics present in the above endpoint. I assume it is due to the fact that the above library doesn't know about the system metrics exposed via logfire. 

I wanted to know if it was possible to add those metrics to the above library.

**Comment by alexmojaki** [comment]
I don't see any way to make this happen. This issue suggests that the library doesn't support things like that: https://github.com/trallnag/prometheus-fastapi-instrumentator/issues/19

It might be possible to create a custom metric reader which passes the system metric measurements to prometheus. But I don't know how prometheus works in general and what that might look like.

**Comment by cyberksh** [comment]
Thanks for this, I'll probably create custom metrics! Sorry for the trouble, missed that issue during search.
