### ISSUE TITLE
Support AmazonBedrock and AsyncAmazonBedrock

### ISSUE THREAD

**Issue by stephenhibbert** [pydantic/logfire#697]
### Description

The Anthropic python SDK includes support for using Anthropic models on Amazon Bedrock. By allowing logfire to use AnthropicBedrock as well as AsyncAnthropicBedrock clients logfire can simply take advantage of this.

https://github.com/anthropics/anthropic-sdk-python/tree/main?tab=readme-ov-file#aws-bedrock

**Comment by alexmojaki** [comment]
Released in v2.11.0!
