### ISSUE TITLE
async sqlalchemy engine support

### ISSUE THREAD

**Issue by mplemay** [pydantic/logfire#713]
### Description

It looks like in `logfire[aiohttp,fastapi,sqlalchemy]>=2.9.0`, the `sqlalchemy` `AsyncEngine` is not supported. Is it possible to add support for this? 

## Code
```python
POSTGRES: Final[AsyncEngine] = create_async_engine(url=POSTGRES_URL, echo=SETTINGS.DEBUG)
logfire.instrument_sqlalchemy(engine=POSTGRES)
```
## Error
```
Argument of type "AsyncEngine" cannot be assigned to parameter "engine" of type "Engine | None" in function "instrument_sqlalchemy"
  Type "AsyncEngine" is not assignable to type "Engine | None"
    "AsyncEngine" is not assignable to "Engine"
    "AsyncEngine" is not assignable to "None"
```

**Comment by alexmojaki** [comment]
Based on https://opentelemetry-python-contrib.readthedocs.io/en/latest/instrumentation/sqlalchemy/sqlalchemy.html, try `logfire.instrument_sqlalchemy(engine=POSTGRES.sync_engine)`

**Comment by mplemay** [comment]
Thanks @alexmojaki

**Comment by alexmojaki** [comment]
Let's make the SDK take care of this, or at least document it.
