### ISSUE TITLE
sklearn instrumentation and in general outdated opentelemetry exstension

### ISSUE THREAD

**Issue by furlat** [pydantic/logfire#72]
Following the tutorial logfire inspect suggested to install the sklearn instrumentation from open telemetry, but the tools does not have any version compatibility check and this can easily lead to issues.

I tried using https://github.com/open-telemetry/opentelemetry-python-contrib/tree/main/instrumentation/opentelemetry-instrumentation-sklearn to expand tracking to sklearn but the package is severely out-dated and tries to import and use non existing methods, I imagine this can be the case for many of the instrumentation suggestions arriving from the community contrib.

ps: loooving Logfire!!

**Comment by Kludex** [comment]
Thanks for the report @furlat :)

I've merged a fix specifically for `sklearn`/`scikit-learn` for now.
