### ISSUE TITLE
Links to GitHub code source

### ISSUE THREAD

**Issue by Kludex** [pydantic/logfire#79]
### Description

You'll be able to go to your GitHub repository directly from the **Logfire UI**, and see the code of a logfire call or exception.

Please let us know if you are interested in this, so we can prioritize it.

**Comment by Kludex** [comment]
Documented here: https://logfire.pydantic.dev/docs/guides/advanced/link-to-code-source/

**Comment by alexmojaki** [comment]
This still needs correcting: https://logfire.pydantic.dev/docs/reference/api/logfire/#logfire.CodeSource.root_path

Something like https://github.com/pydantic/logfire/pull/451#discussion_r1804453006

**Comment by Kludex** [comment]
This is implemented, and @alexmojaki 's comment above was corrected.
