### ISSUE TITLE
Web: Trying to create a new project doesn't display issue with insufficient permissions

### ISSUE THREAD

**Issue by edgarrmondragon** [pydantic/logfire#97]
### Description

<img width="540" alt="Screenshot 2024-05-02 at 12 43 53 p m" src="https://github.com/pydantic/logfire/assets/16805946/2768cbe4-a7f0-4876-bd71-41b559f31741">

Clicking on `Create project` when the user has the "member" role in an organization doesn't do anything. Looking at the Network tab in the browser reveals a 403 status and a response of

```
{"detail":"User does not have sufficient permissions on this organization"}
```

It would be nice to surface this error to the user in a toast or similar.

**Comment by dmontagu** [comment]
Thanks for reporting! Have a fix coming shortly. I think we should actually disable the button/modal entirely if you don't have permissions but at the very least we can start by showing the error _outside_ the browser console.

**Comment by Kludex** [comment]
We solved this. Thanks @dmontagu and @edgarrmondragon 🙏
